# AUTOGENERATED! DO NOT EDIT! File to edit: ../update_classement.ipynb.

# %% auto 0
__all__ = ['get_classement']

# %% ../update_classement.ipynb 7
def get_classement(
    license_number,# le numero de license
):
#    print(license_number)
    if len(df_adherents[df_adherents['Licence'] == license_number]['Class.'].values)>0:
        return df_adherents[df_adherents['Licence'] == license_number]['Class.'].values[0]
    else:
        return ''
